# Generated by Django 4.2.3 on 2023-10-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Readinglist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Readinglist.author')),
                ('categories', models.ManyToManyField(blank=True, to='Readinglist.category')),
                ('topics', models.ManyToManyField(blank=True, to='Readinglist.topic')),
            ],
        ),
    ]
